<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nml</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>NewML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>keywords</string>
			<key>match</key>
			<string>\b(open|def|if|else|case|match|type)\b</string>
			<key>name</key>
			<string>keyword.newml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>type</string>
			<key>match</key>
			<string>\b(int|string|list|unit)\b</string>
			<key>name</key>
			<string>support.function.newml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>type</string>
			<key>match</key>
			<string>\b([0-9]+)</string>
			<key>name</key>
			<string>constant.numeric.newml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>type</string>
			<key>match</key>
			<string>\b([A-Z][a-zA-Z_0-9\.]*)\b</string>
			<key>name</key>
			<string>entity.name.function.newml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>block comment</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.newml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>block comment</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.newml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.newml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.newml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.newml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>type</string>
			<key>match</key>
			<string>([a-zA-Z_][a-zA-Z_0-9]*) *((\(([^\)]*?) *\) *)*)([:]=?)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.newml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.newml</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.newml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>type</string>
			<key>match</key>
			<string>((\{|^)[\s]*\(([^\)]*?) *\) *|(\w+) *)*(=&gt;)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operators</string>
			<key>match</key>
			<string>[\+\-\*/=&lt;&gt;:.\|&amp;#]+</string>
			<key>name</key>
			<string>keyword.newml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.newml</string>
	<key>uuid</key>
	<string>2b984fb6-88fd-4d1a-805b-30071426dbcf</string>
</dict>
</plist>
